version: '3.5'
services:
  app:
      image: dika6/kuis2
      container_name: web-server
      build: 
          context: ./php
          dockerfile: Dockerfile
      depends_on:
          - db
      volumes:
          - ./php/website_sekolah:/var/www/html/
      ports:
          - 8000:80

  db:
      container_name: db
      image: mysql
      restart: always

      environment:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_DATABASE: website_sekolah
          MYSQL_USER: admin
          MYSQL_PASSWORD: 
      ports:
          - 3306:3306

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '3306:80'
      restart: always

      environment:
          PMA_HOST: db
      depends_on: 
          - db